//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ëntärtäïnër.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ëntärtäïnër.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AlabamaMinne {
            get {
                return ResourceManager.GetString("AlabamaMinne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream hava_nagila {
            get {
                return ResourceManager.GetStream("hava_nagila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU KILLED MY TROJAN!\nNow you are going to die.
        ///REST IN PISS, FOREVER MISS.
        ///I WARNED YOU...
        ///HAHA N00B L2P G3T R3KT
        ///You failed at your 1337 h4x0r skillz.
        ///YOU TRIED SO HARD AND GOT SO FAR, BUT IN THE END, YOUR PC WAS STILL FUCKED!
        ///HACKER!\nENJOY BAN!
        ///GET BETTER HAX NEXT TIME xD
        ///HAVE FUN TRYING TO RESTORE YOUR DATA :D
        ///|\/|3|\/|2
        ///BSOD INCOMING
        ///VIRUS PRANK (GONE WRONG)
        ///ENJOY THE NYAN CAT
        ///Get dank antivirus m9!
        ///You are an idiot!\nHA HA HA HA HA HA HA
        ///#MakeMalwareGreatAgain
        ///SOMEBODY ONCE TOLD ME THE MEMZ ARE GONN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillMessages {
            get {
                return ResourceManager.GetString("KillMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\Run
        ///SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
        ///SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run
        ///SOFTWARE\Microsoft\WindowsNT\CurrentVersion\Windows\load.
        /// </summary>
        internal static string RegPaths {
            get {
                return ResourceManager.GetString("RegPaths", resourceCulture);
            }
        }
    }
}
